services:
  vbench:
    
    # Base environment
    image: docker.io/vllm/vllm-openai-rocm:latest
    env_file:
      - ./amd.env
    
    # ==== Benchmark Arguments (will be ignored by docker) ====
    # List of models:
    # --------------------------------------
    # amd/gpt-oss-120b-w-mxfp4-a-fp8
    # amd/Llama-3.3-70B-Instruct-FP8-KV
    # unsloth/Mistral-Small-3.2-24B-Instruct-2506-FP8
    # RedHatAI/gemma-3-27b-it-FP8-dynamic
    # amd/Llama-3.1-8B-Instruct-FP8-KV
    # Qwen/Qwen3-4B-FP8
    # Qwen/Qwen3-1.7B-FP8
    # --------------------------------------
    x-benchmark-args:
      models:
        - "amd/Llama-3.1-8B-Instruct-FP8-KV"
      hf_token: "<hf_token_here>"
      device_type: GPU
      device_name: MI300X
      concurrencies: [1, 4, 16, 64]
      input_lengths: [512, 1024]
      output_lengths: [512, 1024]
      dataset_type: random
      num_iterations: 10
      csv_path: "./results/amd_vllm_integrated_benchmark_results.csv"
      warmup_runs: 1
    # =========================================================

    # Mount devices
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - video
    shm_size: '128gb' 
    cap_add:
      - SYS_PTRACE  # Common for ROCm/debugging
    security_opt:
      - seccomp:unconfined  # disables seccomp profiles
    ipc: host  # High-performance computing often needs host IPC
    network_mode: host  # Use 'host' for maximum network performance

    # Mount benchmark files
    volumes:
      - .:/vbench
    working_dir: /vbench
    entrypoint: ["/bin/sh", "-c"]
    command: ["python3 -u broad_bench.py > results/benchmark.log 2>&1"]
    # Clean up
    restart: "no"